title: "EPIC Guide"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

collections:
  applying:
    name: Applying
    output: true
    permalink: /:collection/:name
    order: 0
  first:
    name: Getting started
    output: true
    permalink: /:collection/:name
    order: 1
  middle:
    name: Work at EPFL
    output: true
    permalink: /:collection/:name
    order: 2
  last:
    name: Graduating
    output: true
    permalink: /:collection/:name
    order: 3
  life:
    name: Life in Lausanne
    output: true
    permalink: /:collection/:name
    order: 4